### ISSUE TITLE
Error Handling when in Edit Session

### ISSUE THREAD

**Issue by TaraKingNRCS** [USDA-NRCS/NRCS-Engineering-Tools---ArcMap#2]
[test_EngTools.txt](https://github.com/USDA-NRCS/NRCS-Engineering-Tools---ArcMap/files/4760182/test_EngTools.txt)

Runoff Curve Number script:  If you remain in an edit session after editing the soils/land use, you'll get a system error.  Suggest trapping the error with a message that a typical user will understand.

**Comment by CEM-NRCS** [comment]
I've got some trapping in my wetlands toolbox that I may be able to port over to the engineering toolbox to exactly address your suggestion. I'll take a look. Thanks!

**Comment by CEM-NRCS** [comment]
Updated Runoff Curve Number to trap any active edit session that is tied to the project geodatabase and to exit and provide the user a meaningful error if so.
