### ISSUE TITLE
NRCS Engineering Tools - Area of Interest Error Code

### ISSUE THREAD

**Issue by jdowney21412** [USDA-NRCS/NRCS-Engineering-Tools---ArcMap#7]
When I am trying to run my area of interest, I am recieving the following error code on multiple attempts:

Executing: DefineAOI F:\Temp Kent\MD_kent_dem_ft Feet "Feature Set" 2
Start Time: Mon May 16 07:53:16 2022
Running script DefineAOI...

Gathering information about input DEM file: MD_kent_dem_ft:
	Projection Name: NAD_1983_2011_UTM_Zone_18N
	XY Linear Units: Meters
	Elevation Values (Z): Feet
	Cell Size: 1.0 x 1.0 Meters

Removing old datasets from FGDB: Temp_EngTools.gdb
	Deleting.....Temp_DEM
	Deleting.....DEMsmooth

Successfully Recreated "Temp_AOI" feature class

	Area of Interest: Temp_AOI
		Area:  2,638,736.66 Sq. Meters
		Acres: 652.05 Acres

Successully Clipped MD_kent_dem_ft using Temp_AOI

Successully Smoothed Temp_DEM

----------------------------------- ERROR Start -----------------------------------
Traceback Info: 
  File "c:\program files (x86)\arcgis\desktop10.8\arcpy\arcpy\geoprocessing\_base.py", line 510, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\program files (x86)\arcgis\desktop10.8\arcpy\arcpy\sa\Functions.py", line 5975, in Wrapper
    max_vertices_per_feature)
  File "c:\program files (x86)\arcgis\desktop10.8\arcpy\arcpy\sa\Utils.py", line 53, in swapper
    result = wrapper(*args, **kwargs)
  File "c:\program files (x86)\arcgis\desktop10.8\arcpy\arcpy\sa\Functions.py", line 5984, in Contour
    max_vertices_per_feature)
  File "C:\NRCS-Engineering-Tools---ArcMap-master\SUPPORT\Define_AOI.py", line 382, in <module>
    arcpy.sa.Contour(DEMsmooth, ContoursTemp, interval, "0", Zfactor)
Error Info: 
    <class 'arcgisscripting.ExecuteError'>: ERROR 000287: Fail to create output feature class.
Failed to execute (Contour).

------------------------------------- ERROR End -----------------------------------

Completed script DefineAOI...
Failed to execute (DefineAOI).
Failed at Mon May 16 08:06:22 2022 (Elapsed Time: 13 minutes 5 seconds)

I am unable to run the Watershed tools functions because of this error code. It started last Monday and has not been resolved. I have spoken with USDA IT and they were not much help on the issue. I am not the only one experiencing this issue talking to some of my colleagues from around the state.

**Comment by CEM-NRCS** [comment]
Do not run the tool to a workspace on a network drive. Workspace folder must be on a local computer drive, otherwise raster processing times out and generates this error.
